apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: s3-to-kafka
spec:
  flows:
    - route:
        from:
          uri: kamelet:aws-s3-source
          steps:
            - log:
                message: ${body}
                loggingLevel: INFO
            - to:
                uri: kamelet:kafka-sink
                parameters:
                  topic: '{{kafka.topic.name}}'
                  bootstrapServers: '{{kafka.bootstrap.server}}'
                  user: '{{kafka.cliente.id}}'
                  password: '{{kafka.client.secret}}'
          parameters:
            accessKey: '{{aws.access.key}}'
            bucketNameOrArn: '{{aws.bucket.name}}'
            region: '{{aws.region}}'
            secretKey: '{{aws.secret.key}}'
  traits:
    mount:
      configs:
        - 'secret:env-cfg-demo'